/*
 *Karl Butler
 * 6/19/2020
 * Colminationg
 * This program takes time input and tasks input and adds the times to give you your total time aswell as the time per task
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Karl Butler
 */
public class Colminationg extends javax.swing.JFrame {
    /**
     * Creates new form Colminationg
     */
    public Colminationg() {
        initComponents();
        start=0;
        end=0;
        num1=0;
        num2=0;
        num3=0;
        timeTotal=0;
        
    }
//this is wehre any globle variable was declared so that there values could be used anywhere in the program.
int start,end,num1,num2,num3,timeTotal;
String task,message;
//these two arrays store the tasks done and the time that those tasks took so that it can be out put latter
ArrayList<String> tasksDone = new ArrayList<>();
ArrayList<Integer> time = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        startTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        taskDone = new javax.swing.JTextField();
        endTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        outPut = new javax.swing.JButton();
        tasksAdded = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(66, 135, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Put Tital here");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, 30));

        startTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeActionPerformed(evt);
            }
        });
        jPanel1.add(startTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, -1));

        jLabel2.setText("Enter time task was strted with out a :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 210, -1));

        jLabel3.setText("What Task did you complete");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 170, -1));

        taskDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskDoneActionPerformed(evt);
            }
        });
        jPanel1.add(taskDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, -1));
        jPanel1.add(endTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, -1));

        jLabel4.setText("Enter Time task was finished with out a :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, -1));

        jButton1.setText("Add Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, -1));

        jLabel5.setText("Enter all Times for a 24 Hour Clock ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, -1));

        outPut.setText("out put");
        outPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outPutActionPerformed(evt);
            }
        });
        jPanel1.add(outPut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 80, -1));
        jPanel1.add(tasksAdded, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTimeActionPerformed

    private void taskDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskDoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskDoneActionPerformed
/*
 * this method is used to retrieve the inputs from the user and send it to the method Time to calculate the time in minutes
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     //total is used to get the total time of each task done
     
        int total;
      
      start=Integer.parseInt(startTime.getText());
      end=Integer.parseInt(endTime.getText());
     total= Time(start,end);

      task=taskDone.getText();
 
      tasksDone.add(task);
      time.add(total);
       
        num3++;
      
        tasksAdded.setText("you have added " + num3 + " tasks");
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
//This method is used to display the final output
    private void outPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outPutActionPerformed
     
        
        String display = "";
for (int i=0;i<=num3-1;i++)
{                
display+="Task:"+(i+1) +" "+tasksDone.get(i) + " time for task "+time.get(i)+" minutes \n";    
timeTotal=timeTotal +time.get(i); 
}
display+="the total time worked is " + timeTotal +" minutes";
JOptionPane.showMessageDialog(null, display);
       
       
    }//GEN-LAST:event_outPutActionPerformed
//this method takes the inputs for times and converts it to time in minutes.
    
    public int Time(int start, int end){
  int hourStart,hourEnd,hour,minT,total;
  double minStart,minEnd,nStart,nEnd,min;  
     nStart=start;
     nEnd=end;
     
      minStart=nStart/100;
      minEnd=nEnd/100; 
      hourStart=start/100;
      hourEnd=end/100;
      
      minStart=(minStart-hourStart)*100;
      minStart=Math.round(minStart);
      
      minEnd=(minEnd-hourEnd)*100;
      minEnd=Math.round(minEnd);
     
     hour=hourEnd-hourStart;
     min=minEnd-minStart;
     
     minT=(int)min;
     
     hour=hour*60;
     
     total=hour+minT;
     
     
     
      
    return total;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colminationg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colminationg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colminationg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colminationg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colminationg().setVisible(true);
                
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField endTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton outPut;
    private javax.swing.JTextField startTime;
    private javax.swing.JTextField taskDone;
    private javax.swing.JLabel tasksAdded;
    // End of variables declaration//GEN-END:variables
}
